name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: supplantr/opine:latest
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: make test
